---
- name: Include legacy tasks
  when:
    - ansible_distribution_version is version('24.04', '<')
  ansible.builtin.include_tasks: legacy.yml
  tags:
    - apt

- name: Include recent tasks
  when:
    - ansible_distribution_version is version('24.04', '>=')
  ansible.builtin.include_tasks: recent.yml
  tags:
    - apt

- name: Update apt cache
  when:
    - apt_force_update
  register: result
  until: not result.failed | bool
  retries: 6
  delay: 10
  ansible.builtin.apt:
    update_cache: true
  tags:
    - apt

- name: Install required packages
  loop:
    - unattended-upgrades
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - apt

- name: Write periodic config
  when:
    - apt_periodic_config_enabled
  ansible.builtin.template:
    src: periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - apt

- name: Write unattended-upgrades config
  when:
    - apt_unattended_config_enabled
  ansible.builtin.template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - apt

- name: Drop redundant configs
  loop: "{{ apt_redundant_configs }}"
  ansible.builtin.file:
    path: "/etc/apt/apt.conf.d/{{ item }}"
    state: absent
  tags:
    - apt

...
